/*
 * @(#)CubeExplorerExporter.java
 * CubeTwister. Copyright © 2020 Werner Randelshofer, Switzerland. MIT License.
 */

package ch.randelshofer.rubik.impexp.cubeexplorer;

import ch.randelshofer.cubetwister.doc.DocumentModel;
import ch.randelshofer.cubetwister.doc.ScriptModel;
import ch.randelshofer.gui.ProgressObserver;
import ch.randelshofer.io.LFWriter;
import ch.randelshofer.rubik.cube.RubiksCube;
import ch.randelshofer.rubik.impexp.Exporter;
import ch.randelshofer.rubik.parser.Node;
import ch.randelshofer.rubik.parser.ScriptParser;
import org.jhotdraw.annotation.Nonnull;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
/**
 * CubeExplorer Exporter.
 * <p>
 * EBNF Productions of the File format of CubeExplorer:
 * <pre>
 * file ::= script {"\r\n" script}
 * script ::= move {" " move} ["(" number "f)"] " // " name
 * move ::= ("R" | "F" | "U" | "D" | "B" | "L") ["'" | "2"]
 * name ::= {letter | digit | space}
 * </pre>
 *
 * @author  Werner Randelshofer
 */
public class CubeExplorerExporter extends JPanel
implements Exporter {
    private final static long serialVersionUID = 1L;
    private DocumentModel documentModel;
    private ScriptParser parser;

    /** Creates new form. */
    public CubeExplorerExporter() {
        initComponents();
        parser = new KociembaENGParser();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        noOptionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        noOptionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noOptionsLabel.setText("No Options Available");
        add(noOptionsLabel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void exportFile(@Nonnull File file, @Nonnull ProgressObserver p) throws IOException {
        PrintWriter out = null;
        RubiksCube cube = new RubiksCube();
        RubiksCube translatedCube = new RubiksCube();

        try {
            LFWriter lfout;
            out = new PrintWriter(new LFWriter(new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), "ISO-8859-1")), "\r\n"));
            String line;
            ArrayList columns = new ArrayList();

            p.setMaximum(documentModel.getScripts().getChildCount());
            int progress = 0;

            HashMap permutationMap = new HashMap();
            Enumeration enumer = documentModel.getScripts().children();
            while (enumer.hasMoreElements()) {
                ScriptModel item = (ScriptModel) enumer.nextElement();
                p.setProgress(++progress);
                p.setNote("Exporting "+item.getName());

                Node parsedScript = item.getParsedScript();
                if (parsedScript == null) {
                    throw new IOException("Can not parse script \""+item.getName()+"\".");
                }
throw new InternalError("not implemented");
/*
                out.print(parser.toString(parsedScript, Collections.EMPTY_MAP));
                out.print(" (");
                out.print(parsedScript.getFaceTurnCount());
                out.print("f) //");
                out.println(item.getName());
 */
            }
        } finally {
            if (out != null) {
                out.close();
            }
        }
    }

    public void setDocumentModel(DocumentModel model) {
        this.documentModel = model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel noOptionsLabel;
    // End of variables declaration//GEN-END:variables

    @Nonnull
    @Override
    public JComponent getComponent() {
        return this;
    }

}
