/*
 * @(#)CubeStickerColorsView.java  2.0  2008-12-23
 *
 * Copyright (c) 2001-2008 Werner Randelshofer, Switzerland.
 * You may not use, copy or modify this file, except in compliance with the
 * accompanying license terms.
 */

package ch.randelshofer.cubetwister.doc;

import ch.randelshofer.gui.*;
import ch.randelshofer.gui.table.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.*;

/**
 * Stickers View.
 *
 * @author  Werner Randelshofer
 * @version 2.0 2008-12-23 Renamed from CubeStickersView to CubeStickerColorsView.
 * <br>1.2 2004-06-21 Made the table striped.
 * <br>1.1 2004-04-11 ComboBox is used as cell renderer where appropriate. 
 * <br>1.0 2001-08-02 Created.
 */
public class CubeStickerColorsView extends AbstractEntityView {
    private final static long serialVersionUID = 1L;
    private CubeStickersTableModel tableModel;
    private CubeModel cubeModel;
    private CubeColorComboBoxModel editorColorComboBoxModel, rendererColorComboBoxModel;
    private DefaultCellEditor colorEditor;
    
    /** Creates new form CubeStickerColorsView */
    public CubeStickerColorsView() {
        initComponents();

        tableModel = new CubeStickersTableModel();
        table.setModel(tableModel);
        table.setDefaultRenderer(CubeColorModel.class, new CubeColorModelCellRenderer());
        
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(50);
        table.getColumnModel().getColumn(2).setPreferredWidth(180);
        //table.getColumnModel().getColumn(3).setPreferredWidth(100);
        table.moveColumn(1, 0);

        table.putClientProperty("Quaqua.Table.style","striped");

        //Set up the editor for the color cells.
        JComboBox comboBox = new JComboBox(editorColorComboBoxModel = new CubeColorComboBoxModel());
        comboBox.setRenderer(new CubeColorModelCellRenderer());
        comboBox.setFont(Fonts.getSmallDialogFont());
        table.setDefaultEditor(CubeColorModel.class, colorEditor = new DefaultCellEditor(comboBox));

        if ("Aqua".equals(UIManager.getLookAndFeel().getID())) {
        comboBox = new JComboBox(rendererColorComboBoxModel = new CubeColorComboBoxModel());
        comboBox.setRenderer(new CubeColorModelCellRenderer());
        comboBox.setFont(Fonts.getSmallDialogFont());
        table.setDefaultRenderer(CubeColorModel.class, new DefaultCellRenderer(comboBox));
        } else {
        table.setDefaultRenderer(CubeColorModel.class, new CubeColorModelCellRenderer());
        }
        //table.setDefaultRenderer(Boolean.class, new DefaultCellRenderer(new JCheckBox()));
        if ("Windows".equals(UIManager.getLookAndFeel().getID())) {
            scrollPane.setBorder(new EmptyBorder(0,0,0,0));
        }
    }

    public void setModel(CubeModel s) {
        if (table.getCellEditor() != null) { 
        table.getCellEditor().stopCellEditing();
        }
        cubeModel = s;
        tableModel.setModel(s);
        editorColorComboBoxModel.setModel(s);
       if (rendererColorComboBoxModel != null) rendererColorComboBoxModel.setModel(s);      
    }
/*
    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.getContentPane().add(new CubeStickerColorsView());
        f.setSize(400,400);
        f.setLocation(10,10);
        f.show();
    }
*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new ch.randelshofer.gui.MutableJTable();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setFont(UIManager.getFont("SmallDialogFont"));

        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JComponent getViewComponent() {
        return this;
    }
    
    public void setModel(EntityModel newValue) {
        setModel((CubeModel) newValue);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private ch.randelshofer.gui.MutableJTable table;
    // End of variables declaration//GEN-END:variables

}
