/*
 * @(#)NotationMacrosView.java  1.1.1  2010-03-28
 *
 * Copyright (c) 2001-2010 Werner Randelshofer, Switzerland.
 * You may not use, copy or modify this file, except in compliance with the
 * accompanying license terms.
 */

package ch.randelshofer.cubetwister.doc;

import ch.randelshofer.gui.table.DefaultCellEditor2;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.PlainDocument;
/**
 * NotationMacrosView.
 *
 * @author Werner Randelshofer
 * @version 1.1.1 2010-03-28 Workaround for IllegaArgumentException in table
 * cell editor field.
 * <br>1.1 2004-06-21 Made the table striped.
 * <br>1.0.1 2004-03-15 Always show the vertical scroll bar.
 * <br>1.0 2001-07-24 Created.
 */
public class NotationMacrosView extends JPanel implements EntityView {
    private final static long serialVersionUID = 1L;
    NotationMacrosTableModel tableModel;
    
    /** Creates new form CubeMacrosView */
    public NotationMacrosView() {
        initComponents();
        
        tableModel = new NotationMacrosTableModel();
        table.setModel(tableModel);
        table.getColumnModel().getColumn(0).setPreferredWidth(70);
        table.getColumnModel().getColumn(1).setPreferredWidth(200);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        table.putClientProperty("Quaqua.Table.style","striped");
        
        DefaultCellEditor cellEditor = new DefaultCellEditor2(new JTextField());
        cellEditor.setClickCountToStart(1);
        table.getColumnModel().getColumn(0).setCellEditor(cellEditor);
        table.getColumnModel().getColumn(1).setCellEditor(cellEditor);
        table.getColumnModel().getColumn(2).setCellEditor(cellEditor);
        //table.setFont(Fonts.getSmallDialogFont());
        //textField.setFont(Fonts.getSmallDialogFont());

    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scrollPane = new javax.swing.JScrollPane();
        table = new ch.randelshofer.gui.MutableJTable();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public void setModel(EntityModel newValue) {
        NotationModel s = (NotationModel) newValue;
        if (table.getCellEditor() != null) {
            table.getCellEditor().stopCellEditing();
        }
        tableModel.setModel(s);
    }
    
    public JComponent getViewComponent() {
        return this;
    }
    
    public void addUndoableEditListener(UndoableEditListener l) {
    }
    
    public void removeUndoableEditListener(UndoableEditListener l) {
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private ch.randelshofer.gui.MutableJTable table;
    // End of variables declaration//GEN-END:variables
    
}
