/* @(#)VirtualCube7Applet.java
 * Copyright (c) 2008 Werner Randelshofer, Switzerland.
 * You may only use this software in accordance with the license terms.
 */

package ch.randelshofer.rubik.virtual;

import ch.randelshofer.rubik.*;
/**
 * VirtualCube7Applet.
 * 
 * 
 * @author Werner Randelshofer
 * @version $Id$
 */
public class VirtualCube7Applet extends AbstractVirtualCubeApplet {
        private final static long serialVersionUID = 1L;

    protected AbstractCubeIdx3D createCube3D() {
        return new Cube7Idx3D();
    }
    protected boolean canBeDisassembled() {
        return false;
    }
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
