/*
 * @(#)VirtualVCube6Applet.java  1.0  2008-08-17
 * Copyright (c) 2008 Werner Randelshofer, Switzerland.
 * You may only use this software in accordance with the license terms.
 */
package ch.randelshofer.rubik.virtual;

import ch.randelshofer.rubik.*;

/**
 * VirtualVCube6Applet.
 *
 *
 * @author Werner Randelshofer
 * @version 1.0 2008-08-17 Created.
 */
public class VirtualVCube6Applet extends AbstractVirtualCubeApplet {

    private final static long serialVersionUID = 1L;

    @Override
    protected AbstractCubeIdx3D createCube3D() {
        return new VCube6Idx3D();
    }

    @Override
    protected boolean canBeDisassembled() {
        return false;
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
