/*
 * @(#)JDnDTable.java  1.0  May 16, 2004
 * Copyright (c) 2004 Werner Randelshofer, Switzerland.
 * You may only use this software in accordance with the license terms.
 */

package ch.randelshofer.gui;

/**
 * JDnDTable.
 *
 * @author  Werner Randelshofer
 * @version 1.0  May 16, 2004  Created.
 */
public class JDnDTable extends MutableJTable {
        private final static long serialVersionUID = 1L;

    /** Creates new form. */
    public JDnDTable() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
