/*
 * @(#)Idx3DPerspectiveRasterizerDemo.java  1.0  2010-05-29
 * 
 * Copyright (c) 2010 Werner Randelshofer, Switzerland.
 * You may not use, copy or modify this file, except in compliance with the
 * accompanying license terms.
 */

/*
 * Idx3DPerspectiveRasterizerDemo.java
 *
 * @author Werner Randelshofer
 * @version 1.0 2010-05-29 Created.
 */
package demos;

import idx3d.*;
import idx3d.idx3d_Texture;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.*;

/**
 *
 * @author werni
 */
@SuppressWarnings("deprecation")
public class Idx3DPerspectiveRasterizerDemo extends javax.swing.JPanel {
    private final static long serialVersionUID = 1L;

    private idx3d_JCanvas canvas;
    
    private idx3d_Rasterizer linearRasterizer,perspectiveRasterizer;

    /** Creates new form Idx3DInteractionDemo */
    public Idx3DPerspectiveRasterizerDemo() {
        initComponents();

        
        linearRasterizer = new idx3d_LinearRasterizer(null);
        perspectiveRasterizer = new idx3d_PerspectiveRasterizer(null);
        
        canvas = new idx3d_JCanvas();
        canvas.setRasterizer(perspectiveRasterizer);
        add(canvas);

        // Create texture
        int size=4;
        BufferedImage bimg=new BufferedImage(size,size,BufferedImage.TYPE_INT_RGB);
        Graphics2D g=bimg.createGraphics();
        g.setBackground(Color.WHITE);
        g.clearRect(0, 0, size, size);
        g.setColor(Color.RED);
        for (int i=0;i<size;i+=2) {
        for (int j=0;j<size;j+=1) {
        g.fillRect(i+j%2,j,1,1);
        }
        }
        g.dispose();
        Image scaledImg=bimg;//.getScaledInstance(64, 64, BufferedImage.SCALE_REPLICATE);
        idx3d_Texture txtr=new idx3d_Texture(scaledImg);


        idx3d_Scene scene = new idx3d_Scene();
        idx3d_Object obj = idx3d_ObjectFactory.BOX(new idx3d_Vector(200, 200, 200));
//        obj.setMaterial(new idx3d_Material(0x666666));
        idx3d_Material mat = new idx3d_Material(txtr);
        //mat.setTexture(null);
        mat.setColor(0xaa1111);
        mat.setFlat(true);
        //mat.setFlat(false);
        mat.setReflectivity(200);
        obj.setMaterial(mat);
        scene.addChild(obj);
        idx3d_Camera cam = new idx3d_Camera();
        cam.setPos(new idx3d_Vector(0, 0, -400));
        scene.addCamera("front", cam);

        cam = new idx3d_Camera();
        cam.setPos(new idx3d_Vector(400, 0, 0));
        scene.addCamera("right", cam);
        scene.setBackgroundColor(Color.BLUE.getRGB());
/*        scene.addLight("light1", new idx3d_Light(new idx3d_Vector(300, 300, 300), 0xffffff, 0xffffff, 100, 50));
        scene.addLight("light2", new idx3d_Light(new idx3d_Vector(300, -300, -300), 0xffffff, 0xffffff, 100, 50));
        scene.addLight("light3", new idx3d_Light(new idx3d_Vector(-300, -300, -300), 0xffffff, 0xffffff, 100, 50));
 */       scene.addLight("KeyLight", new idx3d_Light(new idx3d_Vector(1f, -1f, 1f), 0xffffff, 0xffffff, 100, 100));
        scene.addLight("FillLightRight", new idx3d_Light(new idx3d_Vector(-1f, 0f, 1f), 0x888888, 50, 50));
        scene.addLight("FillLightDown", new idx3d_Light(new idx3d_Vector(0f, 1f, 1f), 0x666666, 50, 50));
        canvas.setScene(scene);
        canvas.setCamera("front");
        canvas.setInteractionMode(idx3d_JCanvas.Interaction.ROTATE);
        canvas.setDebugRenderTime(true);
        
        canvas.addMouseListener( new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (canvas.getRasterizer()==perspectiveRasterizer) {
                    canvas.setRasterizer(linearRasterizer);
                }else{
                    canvas.setRasterizer(perspectiveRasterizer);
                }
                canvas.repaint();
            }
        });

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                JFrame f = new JFrame("Idx3D Perspective correct texture");
                f.add(new Idx3DPerspectiveRasterizerDemo());
                f.setSize(400, 400);
                f.show();
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
