/*
 * @(#)BarrelPlayer.java  1.0  April 13, 2006
 * Copyright (c) 2006 Werner Randelshofer, Switzerland.
 * You may only use this software in accordance with the license terms.
 */

import ch.randelshofer.rubik.player.RubiksBarrelIdx3DPlayerApplet;
import ch.randelshofer.rubik.player.AbstractPlayerApplet;
/**
 * BarrelPlayer.
 * 
 * @author Werner Randelshofer
 * @version 1.0 2006-04-13 Created.
 */
public class BarrelPlayer extends RubiksBarrelIdx3DPlayerApplet {
    private final static long serialVersionUID = 1L;
    public static void main(String args[]) {
        AbstractPlayerApplet.main(new BarrelPlayer(), args);
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * /
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
