/* @(#)DiamondPlayerFlat.java
 * Copyright (c) 2006 Werner Randelshofer, Switzerland. MIT License.
 */
import ch.randelshofer.rubik.player.AbstractPlayerApplet;
import ch.randelshofer.rubik.player.RubiksDiamondGeom3DPlayerApplet;
/**
 * DiamondPlayerFlat.
 * 
 * @author Werner Randelshofer
 * @version $Id$
 */
public class DiamondPlayerFlat extends RubiksDiamondGeom3DPlayerApplet {
    private final static long serialVersionUID = 1L;
    public static void main(String args[]) {
        AbstractPlayerApplet.main(new DiamondPlayerFlat(), args);
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * /
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
