/*
 * @(#)VCube6Player.java  1.0  2008-08-17
 *
 * Copyright (c) 2008 Werner Randelshofer, Switzerland.
 * You may not use, copy or modify this file, except in compliance with the
 * accompanying license terms.
 */

import ch.randelshofer.rubik.player.AbstractPlayerApplet;
import ch.randelshofer.rubik.player.VCube6Idx3DPlayerApplet;
/**
 * VCube6Player.
 * 
 * @author Werner Randelshofer
 * @version 1.0 2008-08-17 Created.
 */
public class VCube6Player extends VCube6Idx3DPlayerApplet {
    private final static long serialVersionUID = 1L;
    public static void main(String args[]) {
        AbstractPlayerApplet.main(new VCube6Player(),args);
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * /
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
