/*
 * @(#)VCube6PlayerFlat.java  1.0  2008-09-16
 *
 * Copyright (c) 2008 Werner Randelshofer, Switzerland.
 * You may not use, copy or modify this file, except in compliance with the
 * accompanying license terms.
 */

import ch.randelshofer.rubik.player.*;
/**
 * VCube6PlayerFlat.
 * 
 * @author Werner Randelshofer
 * @version 1.0 2008-09-16 Created.
 */
public class VCube6PlayerFlat extends VCube6Geom3DPlayerApplet {
    private final static long serialVersionUID = 1L;
    public static void main(String args[]) {
        AbstractPlayerApplet.main(new VCube6PlayerFlat(),args);
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * /
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.FlowLayout());
    }// </editor-fold>//GEN-END:initComponents
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
