/*
 * @(#)VirtualProfessorCube.java  1.0  26. August 2007
 * Copyright (c) 2007 Werner Randelshofer, Switzerland.
 * You may only use this software in accordance with the license terms.
 */
import ch.randelshofer.rubik.virtual.*;


/**
 * Virtual Professor Cube.
 *
 * @author Werner Randelshofer
 * @version 1.0 25. August 2007 Created.
 */
public class VirtualProfessorCube extends VirtualProfessorCubeApplet {
    private final static long serialVersionUID = 1L;
    public static void main(String args[]) {
        AbstractVirtualCubeApplet.main(new VirtualProfessorCube());
    }
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
