/* @(#)VirtualCube7.java
 * Copyright (c) 2008 Werner Randelshofer, Switzerland. MIT License.
 */
import ch.randelshofer.rubik.virtual.*;


/**
 * Virtual Cube 7.
 *
 * @author Werner Randelshofer
 * @version $Id$
 */
public class VirtualCube7 extends VirtualCube7Applet {
        private final static long serialVersionUID = 1L;

    public static void main(String args[]) {
        AbstractVirtualCubeApplet.main(new VirtualCube7());
    }
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
