/* @(#)CubePartsView.java	1.2  2004-06-21
 * Copyright (c) 2004 Werner Randelshofer, Switzerland. MIT License.
 */

package ch.randelshofer.cubetwister.doc;

import ch.randelshofer.gui.*;
import ch.randelshofer.gui.table.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.*;

/**
 * Parts View.
 *
 * @author  Werner Randelshofer
 */
public class CubePartsView extends AbstractEntityView {
    private final static long serialVersionUID = 1L;
    private CubePartsTableModel tableModel;
    private CubeModel cubeModel;
    private CubeColorComboBoxModel editorColorComboBoxModel;
    private CubeColorComboBoxModel rendererColorComboBoxModel;
    private DefaultCellEditor colorEditor;
    
    /** Creates new form CubePartsView */
    public CubePartsView() {
        initComponents();
        
        tableModel = new CubePartsTableModel();
        table.setModel(tableModel);
        
        table.getColumnModel().getColumn(0).setPreferredWidth(80);
        table.getColumnModel().getColumn(1).setPreferredWidth(50);
        table.getColumnModel().getColumn(2).setPreferredWidth(120);
        table.getColumnModel().getColumn(3).setPreferredWidth(120);
        table.moveColumn(1, 0);

        table.setFont(Fonts.getSmallDialogFont());
        table.putClientProperty("Quaqua.Table.style","striped");
        
        //Set up the renderer and the editor for the color cells.
        //table.setDefaultRenderer(CubeColorModel.class, new CubeColorModelCellRenderer());
        
        JComboBox comboBox = new JComboBox(editorColorComboBoxModel = new CubeColorComboBoxModel());
        comboBox.setRenderer(new CubeColorModelCellRenderer());
        comboBox.setFont(Fonts.getSmallDialogFont());
        table.setDefaultEditor(CubeColorModel.class, colorEditor = new DefaultCellEditor(comboBox));
    
        if ("Aqua".equals(UIManager.getLookAndFeel().getID())) {
        
        comboBox = new JComboBox(rendererColorComboBoxModel = new CubeColorComboBoxModel());
        comboBox.setRenderer(new CubeColorModelCellRenderer());
        comboBox.setFont(Fonts.getSmallDialogFont());
        table.setDefaultRenderer(CubeColorModel.class, new DefaultCellRenderer(comboBox));
        } else {
        table.setDefaultRenderer(CubeColorModel.class, new CubeColorModelCellRenderer());
        }
        
        //table.setDefaultRenderer(Boolean.class, new DefaultCellRenderer(new JCheckBox()));
        //table.setDefaultEditor(Boolean.class, new DefaultCellEditor(new JCheckBox()));
        if ("Windows".equals(UIManager.getLookAndFeel().getID())) {
            scrollPane.setBorder(new EmptyBorder(0,0,0,0));
        }
    }
    
    public void setModel(CubeModel s) {
        if (table.getCellEditor() != null) { 
        table.getCellEditor().stopCellEditing();
        }
        cubeModel = s;
        tableModel.setModel(s);
        editorColorComboBoxModel.setModel(s);
        if (rendererColorComboBoxModel != null) rendererColorComboBoxModel.setModel(s);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scrollPane = new javax.swing.JScrollPane();
        table = new ch.randelshofer.gui.MutableJTable();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public JComponent getViewComponent() {
        return this;
    }
    
    public void setModel(EntityModel newValue) {
        setModel((CubeModel) newValue);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private ch.randelshofer.gui.MutableJTable table;
    // End of variables declaration//GEN-END:variables
    
}
