/*
 * @(#)ScriptMacrosView.java
 * CubeTwister. Copyright © 2020 Werner Randelshofer, Switzerland. MIT License.
 */
package ch.randelshofer.cubetwister.doc;

import ch.randelshofer.gui.Fonts;
import ch.randelshofer.gui.table.DefaultCellEditor2;
import org.jhotdraw.annotation.Nonnull;
import org.jhotdraw.annotation.Nullable;

import javax.swing.DefaultCellEditor;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.event.UndoableEditListener;

/**
 * ScriptMacrosView.
 *
 * @author Werner Randelshofer
 */
public class ScriptMacrosView extends JPanel implements EntityView {
    private final static long serialVersionUID = 1L;

    ScriptMacrosTableModel tableModel;

    /** Creates new form CubeMacrosView */
    public ScriptMacrosView() {
        initComponents();


        tableModel = new ScriptMacrosTableModel();
        table.setModel(tableModel);
        table.getColumnModel().getColumn(0).setPreferredWidth(70);
        table.getColumnModel().getColumn(1).setPreferredWidth(200);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        table.putClientProperty("Quaqua.Table.style", "striped");

        DefaultCellEditor cellEditor = new DefaultCellEditor2(new JTextField());
        cellEditor.setClickCountToStart(1);
        table.getColumnModel().getColumn(0).setCellEditor(cellEditor);
        table.getColumnModel().getColumn(1).setCellEditor(cellEditor);
        table.getColumnModel().getColumn(2).setCellEditor(cellEditor);
        table.setFont(Fonts.getSmallDialogFont());
        if ("Windows".equals(UIManager.getLookAndFeel().getID())) {
            scrollPane.setBorder(new EmptyBorder(0, 0, 0, 0));
        }
    }

    public void setModel(@Nullable ScriptModel s) {
        if (table.getCellEditor() != null) {
            table.getCellEditor().stopCellEditing();
        }
        tableModel.setModel((s == null) ? null : s);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        scrollPane = new javax.swing.JScrollPane();
        table = new ch.randelshofer.gui.MutableJTable();

        setLayout(new java.awt.BorderLayout());

        scrollPane.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPane.setViewportView(table);

        add(scrollPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void setModel(EntityModel newValue) {
        setModel((ScriptModel) newValue);
    }

    @Nonnull
    public JComponent getViewComponent() {
        return this;
    }

    public void addUndoableEditListener(UndoableEditListener l) {
    }

    public void removeUndoableEditListener(UndoableEditListener l) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private ch.randelshofer.gui.MutableJTable table;
    // End of variables declaration//GEN-END:variables
}
