/* @(#)DefaultViewer.java
 * Copyright (c) 2001 Werner Randelshofer, Switzerland. MIT License.
 */

package ch.randelshofer.gui;

import org.jhotdraw.annotation.Nonnull;

import java.awt.Component;

/**
 * Calls object.toString() and displays this in a JLabel.
 *
 * @author  Werner Randelshofer
 */
public class DefaultViewer 
extends javax.swing.JPanel implements Viewer {
    private final static long serialVersionUID = 1L;

    /** Creates new form DefaultViewer */
    public DefaultViewer() {
        initComponents();
    }

    @Nonnull
    public Component getComponent(Component parent, Object value) {
        if (value instanceof Object[]) {
            return getComponent(parent, (Object[]) value);
        } else {
            label.setText((value == null) ? "" : value.toString());
        }
        return this;
    }

    @Nonnull
    public Component getComponent(Component parent, @Nonnull Object[] values) {
        StringBuilder buf = new StringBuilder();
        for (int i = 0; i < values.length; i++) {
            if (i > 0) {
                buf.append(' ');
            }
            buf.append((values[i] == null) ? "" : values[i].toString());
        }
        label.setText(buf.toString());
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label = new javax.swing.JLabel();
        
        setLayout(new java.awt.BorderLayout());
        
        label.setText("jLabel1");
        add(label, java.awt.BorderLayout.NORTH);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
